// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cryptalk_Provisioner.Migrations
{
    [DbContext(typeof(ProvisionerDbContext))]
    [Migration("20250811044048_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cryptalk_Provisioner.Models.Allocation", b =>
                {
                    b.Property<string>("InstallId")
                        .HasColumnType("text")
                        .HasColumnName("install_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("Fqdn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fqdn");

                    b.Property<string>("IPv4")
                        .HasColumnType("text")
                        .HasColumnName("ipv4");

                    b.Property<string>("IPv6")
                        .HasColumnType("text")
                        .HasColumnName("ipv6");

                    b.HasKey("InstallId");

                    b.HasIndex("Fqdn")
                        .IsUnique();

                    b.ToTable("allocations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
